
# Important:
# Check out the MiniMessage docs to see how to properly use colors in this config.
# https://docs.advntr.dev/minimessage/format

# Scoreboard doesn't allow leagcy color codes.
# You can add more lines to the scoreboard.
# The scoreboard also supports PlaceholderAPI!

# Please visit 'https://github.com/NotAzex/neon-java/blob/main/placeholders'
# to see all the placeholders and what they do.

# %player% returns the name of the player.