name: Neon
version: '1.1.5'
main: org.azex.neon.Neon
api-version: '1.20'
softdepend: [PlaceholderAPI]
depend: [WorldGuard]
authors: [ Azex ]
description: Neon, but it's rewritten in Java
website: https://discord.gg/nKEa5NxRew
commands:
  wins:
    description: Returns the wins of a player.
  givewins:
    description: Gives a player wins.
    permission: neon.admin
  removewins:
    description: Removes wins from a player.
    permission: neon.admin
  clearwins:
    description: Clears the wins of a player.
    permission: neon.admin
  givealive:
    description: Gives items to alive people.
    permission: neon.admin
  givedead:
    description: Gives items to dead people.
    permission: neon.admin
  kickalive:
    description: Kicks alive people.
    permission: neon.admin
  kickdead:
    description: Kicks dead people.
    permission: neon.admin
  kickall:
    description: Kicks everyone except people with the permission 'neon.kick'.
    permission: neon.admin
  killalive:
    description: Kills alive people.
    permission: neon.admin
  killdead:
    description: Kills dead people.
    permission: neon.admin
  rejoin:
    description: Lets you toggle rejoining and change the time of it.
    permission: neon.admin
  ad:
    description: Lets you send, delete and create custom ads.
    permission: neon.admin
  clearalive:
    description: Clears the inventories of alive people.
    permission: neon.admin
  cleardead:
    description: Clears the inventories of dead people.
    permission: neon.admin
  prize:
    description: Sets the prize.
    permission: neon.admin
  warp:
    description: Allows you to create warps that you can teleport to.
  staffchat:
    description: Allows you to communicate with other staff.
    permission: neon.admin
    aliases: sc
  event:
    description: Sets the event.
    permission: neon.admin
  hunger:
    description: Toggles hunger using events.
    permission: neon.admin
  cleartokens:
    description: Clears the revives of a player.
    permission: neon.admin
    aliases: clearrevives
  listclear:
    description: Clears the alive & dead list and then adds everyone to the dead list.
    permission: neon.admin
  timer:
    description: Starts a timer.
    permission: neon.admin
  tokenusage:
    description: Used for toggling token usage.
    permission: neon.admin
  token:
    description: Used for accepting/denying tokens of players.
    permission: neon.admin
  userevive:
    description: You can use a token if you have any with this command.
  neon:
    description: Used for reloading the config of Neon.
    permission: neon.admin
  break:
    description: Toggles breaking using WorldGuard.
    permission: neon.admin
  build:
    description: Toggles building using WorldGuard.
    permission: neon.admin
  flow:
    description: Toggles flowing using WorldGuard and events.
    permission: neon.admin
  pvp:
    description: Toggles PvP using WorldGuard and events.
    permission: neon.admin
  falldamage:
    description: Toggles fall damage using WorldGuard.
    permission: neon.admin
  revival:
    description: Starts/ends a chat revival.
    permission: neon.admin
  revive:
    description: Revive a player.
    permission: neon.admin
  core:
    description: Tells you what Neon is.
  alive:
    description: Returns the alive list.
  dead:
    description: Returns the dead list.
  mutechat:
    description: Toggles the chat.
    permission: neon.admin
  reviveall:
    description: Revives all players.
    permission: neon.admin
  reviverecent:
    description: Revives players who have died recently.
    permission: neon.admin
  unrevive:
    description: Unrevives an alive player.
    permission: neon.admin
  spawn:
    description: Teleports player to spawn.
  setspawn:
    description: Sets the spawn location.
    permission: neon.admin
  tokens:
    description: Returns the tokens of someone.
    aliases: revives
  removetokens:
    description: Removes tokens from someone.
    permission: neon.admin
    aliases: removerevive
  givetokens:
    description: Gives tokens to someone.
    permission: neon.admin
    aliases: giverevive
  hide:
    description: Hides all players to the sender.
  tpalive:
    description: Teleports alive players to the sender.
    permission: neon.admin
  tpdead:
    description: Teleports dead players to the sender.
    permission: neon.admin
  tpall:
    description: Teleports all players to the sender.
    permission: neon.admin

