
# Important:
# Check out the MiniMessage docs to see how to properly use colors for messages.
# https://docs.advntr.dev/minimessage/format

# Scoreboard allows legacy color codes ('§7') to be used.
# You can add more lines to the scoreboard.
# The scoreboard also supports PlaceholderAPI!

# Please visit 'https://github.com/NotAzex/neon-java/blob/main/placeholders'
# to see all the placeholders and what they do.

# %player% returns the name of the player.

WorldGuard:
  World: world
  Region: arena
Customization:
  Prefix: <light_purple>☄
  Color1: <light_purple>
  Color2: <gray>
Sounds:
  Main: BLOCK_NOTE_BLOCK_PLING
  Error: BLOCK_NOTE_BLOCK_BASS
  Pitch: 1
  Volume: 100
Other:
  EnableBackups: true
  BackupFrequency: 3
Scoreboard:
  Enable: true
  Title: §5☄ Neon
  Lines:
    - ""
    - " §7| &fAlive: &5%alive_size%"
    - " §7| &fDead: &5%dead_size%"
    - " §7| &fTokens: &5%tokens_%player%%"
    - " "
    - "§7§oEdit this in the config of Neon."